server:
  port: 8183
spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xx6xx/cloud_config     # 配置Git仓库的地址
          username: xx6xx                                                      # Git仓库的账号
          password: dcc1234                                                     # Git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.6.251:8761/eureka/
  #服务中心的信息显示（如果IP地址不显示的话，进行配置）ip:port
  instance:
    instance-id: 192.168.6.37:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: 192.168.6.37